### ISSUE TITLE
AttributeError: `get_metrics_history` object has no `items` on v1.67.2

### ISSUE THREAD

**Issue by ReenigneArcher** [PureStorage-OpenConnect/py-pure-client#175]
Given the following code:

```python
metrics = pure1_client.get_metrics_history(
            aggregation='max',
            end_time=now,  # now evaluated to 1747077929000
            names=['array_total_load'],
            resource_ids=[redacted],
            resolution=180000,
            start_time=one_day_ago,  # one_day_ago evaluated to 1746991529000
        )
        try:
            metrics.items = [i for i in metrics.items]
            metric_items.extend(metrics.items)
        except AttributeError as e:
            print(f"Error: {e}")
            print(metrics)
```

I get an attribute error:

```
Error: 'ErrorResponse' object has no attribute 'items'
{'errors': [{'context': "String literals must be enclosed in single (') "
                        'quotes: ["\'m\'", "\'a\'", "\'x\'"]',
             'message': 'Invalid value'}],
 'headers': <bound method ResponseHeaders.to_dict of {'x_ratelimit_limit_minute': '2000',
 'x_ratelimit_limit_second': '100',
 'x_ratelimit_remaining_minute': '1687',
 'x_ratelimit_remaining_second': '99',
 'x_request_id': 'redacted'}>,
 'status_code': 400}
```

Everything works fine on 1.66. I am not sure if any of the 1.67 versions work. It takes an extremely long time to compile due to https://github.com/PureStorage-OpenConnect/py-pure-client/issues/87

I didn't see anything obvious in the changelog that could cause this.

**Comment by mtillajev** [comment]
as per documentation for `agregation` 
>Aggregation needed on the metric data. Valid values are `avg` and `max`. Single quotes are required around all strings. Latency metrics averages are weighted by the IOPS.

Have you tried `aggregation="'max'"` instead of `aggregation='max'`, because first one will be quoted string (which is required according to documentation)?

> It takes an extremely long time to compile due to https://github.com/PureStorage-OpenConnect/py-pure-client/issues/87

could you please add steps to repro to the mentioned issue? It'll help us to resolve it.

**Comment by mtillajev** [comment]
oh, but it should be quoted automatically, https://github.com/PureStorage-OpenConnect/py-pure-client/blob/d88455dab0f729dcc6edbd6d0fc97867fdb3441f/pypureclient/pure1/Pure1_1_5/api/metrics_api.py#L334, let me take closer look

**Comment by mtillajev** [comment]
` _query_params.append(('aggregation', quote_strings(_params['aggregation']))) `

should be  `_query_params.append(('aggregation', quote_string(_params['aggregation']))) ` 
I'll prepare fix (and new release) shortly , sorry for inconvenience

**Comment by mtillajev** [comment]
[1.67.3](https://github.com/PureStorage-OpenConnect/py-pure-client/releases/tag/1.67.3) with fix is released, could you give it a try, please?

**Comment by mtillajev** [comment]
checking

**Comment by mtillajev** [comment]
it's another issue :(, working on the fix

**Comment by mtillajev** [comment]
addressed by [1.67.4](https://github.com/PureStorage-OpenConnect/py-pure-client/releases/tag/1.67.4)

**Comment by ReenigneArcher** [comment]
Everything I am using seems to be working in 1.67.4. Thank you!
